config/routes.rb
Rails.application.routes.draw do
  resources :spells
  resources :items
  resources :characters
  resources :terrains do
    collection do
      get 'field'
    end
  end
  resources :animals

  root to: 'animals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :element, :power_type, :life, :will)
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.haml
= form_for @animal do |f|
  - if @animal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@animal.errors.count, "error")} prohibited this animal from being saved:"
      %ul
        - @animal.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :element
    = f.text_field :element
  .field
    = f.label :power_type
    = f.text_field :power_type
  .field
    = f.label :life
    = f.number_field :life
  .field
    = f.label :will
    = f.number_field :will
  .actions
    = f.submit 'Save'

app/views/animals/edit.html.haml
%h1 Editing animal

= render 'form'

= link_to 'Show', @animal
\|
= link_to 'Back', animals_path

app/views/animals/index.html.haml
%h1 Listing animals

%table.table
  %thead
    %tr
      %th Name
      %th Element
      %th Power type
      %th Life
      %th Will
      %th
      %th
      %th

  %tbody
    - @animals.each do |animal|
      %tr
        %td= animal.name
        %td= animal.element
        %td= animal.power_type
        %td= animal.life
        %td= animal.will
        %td= link_to 'Show', animal
        %td= link_to 'Edit', edit_animal_path(animal)
        %td= link_to 'Destroy', animal, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Animal', new_animal_path

app/views/animals/new.html.haml
%h1 New animal

= render 'form'

= link_to 'Back', animals_path

app/views/animals/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @animal.name
%p
  %b Element:
  = @animal.element
%p
  %b Power type:
  = @animal.power_type
%p
  %b Life:
  = @animal.life
%p
  %b Will:
  = @animal.will

= link_to 'Edit', edit_animal_path(@animal)
\|
= link_to 'Back', animals_path