config/routes.rb
Rails.application.routes.draw do
  resources :spells
  resources :items
  resources :characters
  resources :terrains do
    collection do
      get 'field'
    end
  end
  resources :animals

  root to: 'animals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/character.rb
class Character < ApplicationRecord
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :set_character, only: [:show, :edit, :update, :destroy]

  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render :show, status: :created, location: @character }
      else
        format.html { render :new }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    respond_to do |format|
      if @character.update(character_params)
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { render :show, status: :ok, location: @character }
      else
        format.html { render :edit }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    respond_to do |format|
      format.html { redirect_to characters_url, notice: 'Character was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:name, :class, :power)
    end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.haml
= form_for @character do |f|
  - if @character.errors.any?
    #error_explanation
      %h2= "#{pluralize(@character.errors.count, "error")} prohibited this character from being saved:"
      %ul
        - @character.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :class
    = f.text_field :class
  .field
    = f.label :power
    = f.number_field :power
  .actions
    = f.submit 'Save'

app/views/characters/edit.html.haml
%h1 Editing character

= render 'form'

= link_to 'Show', @character
\|
= link_to 'Back', characters_path

app/views/characters/index.html.haml
%h1 Listing characters

%table.table
  %thead
    %tr
      %th Name
      %th Class
      %th Power
      %th
      %th
      %th

  %tbody
    - @characters.each do |character|
      %tr
        %td= character.name
        %td= character.class
        %td= character.power
        %td= link_to 'Show', character
        %td= link_to 'Edit', edit_character_path(character)
        %td= link_to 'Destroy', character, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Character', new_character_path

app/views/characters/new.html.haml
%h1 New character

= render 'form'

= link_to 'Back', characters_path

app/views/characters/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @character.name
%p
  %b Class:
  = @character.class
%p
  %b Power:
  = @character.power

= link_to 'Edit', edit_character_path(@character)
\|
= link_to 'Back', characters_path