config/routes.rb
Rails.application.routes.draw do
  resources :spells
  resources :items
  resources :characters
  resources :terrains do
    collection do
      get 'field'
    end
  end
  resources :animals

  root to: 'animals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spell.rb
class Spell < ApplicationRecord
end

app/controllers/spells_controller.rb
class SpellsController < ApplicationController
  before_action :set_spell, only: [:show, :edit, :update, :destroy]

  # GET /spells
  # GET /spells.json
  def index
    @spells = Spell.all
  end

  # GET /spells/1
  # GET /spells/1.json
  def show
  end

  # GET /spells/new
  def new
    @spell = Spell.new
  end

  # GET /spells/1/edit
  def edit
  end

  # POST /spells
  # POST /spells.json
  def create
    @spell = Spell.new(spell_params)

    respond_to do |format|
      if @spell.save
        format.html { redirect_to @spell, notice: 'Spell was successfully created.' }
        format.json { render :show, status: :created, location: @spell }
      else
        format.html { render :new }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spells/1
  # PATCH/PUT /spells/1.json
  def update
    respond_to do |format|
      if @spell.update(spell_params)
        format.html { redirect_to @spell, notice: 'Spell was successfully updated.' }
        format.json { render :show, status: :ok, location: @spell }
      else
        format.html { render :edit }
        format.json { render json: @spell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spells/1
  # DELETE /spells/1.json
  def destroy
    @spell.destroy
    respond_to do |format|
      format.html { redirect_to spells_url, notice: 'Spell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spell
      @spell = Spell.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spell_params
      params.require(:spell).permit(:type, :characteristic)
    end
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/views/spells/_form.html.haml
= form_for @spell do |f|
  - if @spell.errors.any?
    #error_explanation
      %h2= "#{pluralize(@spell.errors.count, "error")} prohibited this spell from being saved:"
      %ul
        - @spell.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :type
    = f.text_field :type
  .field
    = f.label :characteristic
    = f.text_field :characteristic
  .actions
    = f.submit 'Save'

app/views/spells/edit.html.haml
%h1 Editing spell

= render 'form'

= link_to 'Show', @spell
\|
= link_to 'Back', spells_path

app/views/spells/index.html.haml
%h1 Listing spells

%table.table
  %thead
    %tr
      %th Type
      %th Characteristic
      %th
      %th
      %th

  %tbody
    - @spells.each do |spell|
      %tr
        %td= spell.type
        %td= spell.characteristic
        %td= link_to 'Show', spell
        %td= link_to 'Edit', edit_spell_path(spell)
        %td= link_to 'Destroy', spell, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Spell', new_spell_path

app/views/spells/new.html.haml
%h1 New spell

= render 'form'

= link_to 'Back', spells_path

app/views/spells/show.html.haml
%p#notice= notice

%p
  %b Type:
  = @spell.type
%p
  %b Characteristic:
  = @spell.characteristic

= link_to 'Edit', edit_spell_path(@spell)
\|
= link_to 'Back', spells_path