config/routes.rb
Rails.application.routes.draw do
  resources :spells
  resources :items
  resources :characters
  resources :terrains do
    collection do
      get 'field'
    end
  end
  resources :animals

  root to: 'animals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.haml
%nav{class: "navbar navbar-default"}
  .container-fluid
    .navbar-header
      %button{class: "navbar-toggle collapsed", id:"menu-toggle", type: "button", data: {toggle: 'collapse', target: "#navbar-main-top"}, aria: {expanded: "false"}}
        %span{class: "sr-only"}Toggle navigation
        %span{class: "icon-bar"}
        %span{class: "icon-bar"}
        %span{class: "icon-bar"}

    %ul{class: " nav navbar-nav"}
      %li
        = link_to "Animals", root_path
      %li
        = link_to "Items", items_path
      %li
        = link_to "Terrains", terrains_path
      %li
        = link_to 'Spells', spells_path
      %li
        = link_to 'Characters', characters_path
      %li
        = link_to 'Field', field_terrains_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type", 'width': 'device-width', 'initial-scale': '1.0'}/
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : "Fantastic Animals"
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Animals'}"}
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %header
      = render 'layouts/navigation'
    %main{role: 'main', id: 'main-container'}
      = yield